apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s
  
patches:
  - target:
      kind: Ingress
      name: kadianai-website
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: kadianai-website

  - target:
      kind: HorizontalPodAutoscaler
      name: kadianai-website
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: kadianai-website
